image:
  repository: "harbor.starburstdata.net/starburstdata/hive"
  tag: "356.0.0"
  pullPolicy: "IfNotPresent"
# docker pull harbor.starburstdata.net/starburstdata/hive:356.0.0

registryCredentials:
  enabled: true
  registry: harbor.starburstdata.net/starburstdata
  username: redhat
  password: JBXjLPv6Scch5t8Dk2zLnZhgS

# database:
#   type: internal
#   internal:
#     image:
#        repository: "registry.redhat.io/rhscl/postgresql-96-rhel7"
#        tag: "latest"
#     env:
#       - name: POSTGRESQL_DATABASE
#         value: "hive"
#       - name: POSTGRESQL_USER
#         value: "hive"
#       - name: POSTGRESQL_PASSWORD
#         value: "HivePass1234"
#     volume:
#       persistentVolumeClaim:
#        storageClassName: ocs-storagecluster-ceph-rbd
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: "2Gi"
#     resources:
#       requests:
#         memory: "1Gi"
#         cpu: 2
#       limits:
#         memory: "1Gi"
#         cpu: 2
#     driver: "org.postgresql.Driver"
#     port: 5432
#     databaseName: "hive"
#     databaseUser: "hive"
#     databasePassword: "HivePass1234"

database:
  type: external
  external:
    jdbcUrl: "jdbc:postgresql://postgresql.license-plate-recognition.svc.cluster.local:5432/pgdb"
    driver: "org.postgresql.Driver"
    user: postgres
    password: postgres

catalogs:
  tpcds-testdata: |
    connector.name=tpcds
  s3: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://hive:9083
    hive.s3.endpoint=http://s3.data.local
    hive.s3.signer-type=S3SignerType
    hive.s3.path-style-access=true
    hive.s3.staging-directory=/tmp
    hive.s3.ssl.enabled=false
    hive.s3.sse.enabled=false
    hive.s3.aws-access-key="7NS6UR50MP07EH5PQZ51"
    hive.s3.aws-secret-key="I0v9WC0XchfxHx3tPwj0a8JiMk2zUoq99LZHMj7M"
    hive.s3.use-instance-credentials=false
  # postgresql-internal: |
  #   connector.name=postgresql
  #   connection-url=jdbc:postgresql://postgresql:5432/hive
  #   connection-user=hive
  #   connection-password=HivePass1234
  postgresql-lpr: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgresql.license-plate-recognition.svc.cluster.local:5432/pgdb
    connection-user=postgres
    connection-password=postgres

# objectStorage:
#   awsS3:
#     region: us-east-1
#     endpoint: "http://s3.data.local"
#     accessKey: "7NS6UR50MP07EH5PQZ51"
#     secretKey: "I0v9WC0XchfxHx3tPwj0a8JiMk2zUoq99LZHMj7M"
#     pathStyleAccess: true

#heapSizePercentage: 85

resources:
  requests:
    memory: "1Gi"
    cpu: 1
  limits:
    memory: "1Gi"
    cpu: 1

