image:
  repository: "harbor.starburstdata.net/starburstdata/starburst-enterprise"
  tag: "356-e.0"
  pullPolicy: "IfNotPresent"
#docker pull harbor.starburstdata.net/starburstdata/starburst-enterprise:356-e.0
#docker pull harbor.starburstdata.net/starburstdata/starburst-enterprise:355-e
initImage:
  repository: "harbor.starburstdata.net/starburstdata/starburst-enterprise-init"
  tag: "356.0.0"
  pullPolicy: "IfNotPresent"
#docker pull harbor.starburstdata.net/starburstdata/starburst-enterprise-init:356.0.0
#docker pull harbor.starburstdata.net/starburstdata/starburst-enterprise-init:355.0.0
registryCredentials:
  enabled: true
  registry: harbor.starburstdata.net/starburstdata
  username: redhat
  password: JBXjLPv6Scch5t8Dk2zLnZhgS

coordinator:
  resources:
    requests:
      memory: "6Gi"
      cpu: 2
    limits:
      memory: "6Gi"
      cpu: 2
      
worker:
  replicas: 1
  resources:
    requests:
      memory: "8Gi"
      cpu: 2
    limits:
      memory: "8Gi"
      cpu: 2

catalogs:
  tpcds-testdata: |
    connector.name=tpcds
  s3: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://hive:9083
    hive.s3.endpoint=http://s3.data.local
    hive.s3.signer-type=S3SignerType
    hive.s3.path-style-access=true
    hive.s3.staging-directory=/tmp
    hive.s3.ssl.enabled=false
    hive.s3.sse.enabled=false
    hive.s3.aws-access-key="7NS6UR50MP07EH5PQZ51"
    hive.s3.aws-secret-key="I0v9WC0XchfxHx3tPwj0a8JiMk2zUoq99LZHMj7M"

starburstPlatformLicense: mylicense